import { EB_Garamond } from "next/font/google";
import "./globals.css";
import Navbar from "../components/Navbar"
import Footer from "../components/Footer"

const ebGaramond = EB_Garamond({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">

      <body className={ebGaramond.className}>
        <Navbar /> 
        {children}

        <Footer />
      </body>
    </html>
  );
}
